"use client";

import { ArrowLeft, Check, CircleDashed, Clock3, ExternalLink, FileKey2, LockKeyhole, PackageCheck, Play, ShieldCheck, Split } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { RunAction, WorkflowRun, Workflow } from "@/lib/workflow/schema";

const icons = { event: PackageCheck, approval: ShieldCheck, condition: Split, payment: LockKeyhole, proof: FileKey2 };

export function RunView({ workflow, onBack }: { workflow: Workflow; onBack: () => void }) {
  const [run, setRun] = useState<WorkflowRun | null>(null); const [busy, setBusy] = useState(true); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/runs", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ workflow }) }).then((response) => response.json()).then((data: { run: WorkflowRun }) => setRun(data.run)).catch(() => setError("Could not create the run. Please try again.")).finally(() => setBusy(false)); }, [workflow]);
  const steps = useMemo(() => workflow.nodes.map((node) => ({ ...node, done: run?.nodeRuns[node.id] === "completed" || run?.nodeRuns[node.id] === "verified", status: run?.nodeRuns[node.id] || "waiting", Icon: icons[node.kind] })), [workflow, run]);
  const next = steps.find((step) => !step.done && (step.kind === "event" || step.kind === "approval") && step.status === "ready");
  const completed = steps.filter((step) => step.done).length; const complete = run?.status === "completed"; const progress = steps.length ? Math.round(completed / steps.length * 100) : 0;
  const advance = async () => {
    if (!run || !next) return; setBusy(true); setError("");
    try { const action: RunAction = { type: "complete_node", nodeId: next.id }; const response = await fetch("/api/runs/advance", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ run, action, workflow }) }); if (!response.ok) throw new Error(); setRun((await response.json() as { run: WorkflowRun }).run); } catch { setError("Execution could not continue. Your current state is safe—try again."); } finally { setBusy(false); }
  };
  const nextActionLabel = next?.kind === "event" ? "Complete event" : next?.kind === "approval" ? "Approve step" : "Continue";
  return <div className="run-page page"><div className="run-top"><button className="icon-button" onClick={onBack}><ArrowLeft size={18} /></button><div><small>{workflow.name.toUpperCase()}</small><h1>Run #{run?.id.slice(-3) || "001"}</h1></div><span className={`run-state s${complete ? 3 : 1}`}><i />{complete ? "Execution complete" : next ? "Action required" : "Waiting"}</span></div>
    <div className="run-layout"><section className="run-panel"><div className="run-summary"><div><small>WORKFLOW EXECUTION</small><h2>{complete ? "Agreement executed" : "Conditions in progress"}</h2><p>{complete ? "Every step completed and the final proof was created." : "Complete the ready action to advance this workflow."}</p></div><span className="progress-number">{progress}<small>%</small></span></div><div className="step-list">{steps.map((step) => { const Icon = step.Icon; const active = !step.done && step.id === next?.id; return <div className={`run-step ${step.done ? "done" : ""} ${active ? "active" : ""}`} key={step.id}><span className="step-icon">{step.done ? <Check size={17} /> : active ? <CircleDashed size={17} /> : <Icon size={17} />}</span><div><b>{step.label}</b><small>{step.detail}</small></div><span className="step-status">{step.done ? (step.kind === "proof" ? "Verified" : "Completed") : step.status === "blocked" ? "Blocked" : active ? "Ready" : "Waiting"}</span></div>; })}</div>{error && <p className="run-error">{error}</p>}<button className="run-action" disabled={!next || busy || complete} onClick={advance}>{busy ? "Advancing securely..." : complete ? "Run complete" : next ? <><Play size={17} />{nextActionLabel}</> : "Waiting for upstream steps"}</button></section>
    <aside className="run-context"><div className="context-card"><small>WORKFLOW</small><h3>{workflow.name}</h3><p className="workflow-description">{workflow.description}</p><dl><div><dt>Nodes</dt><dd>{workflow.nodes.length}</dd></div><div><dt>Connections</dt><dd>{workflow.edges.length}</dd></div><div><dt>Execution</dt><dd>{complete ? "Completed" : "In progress"}</dd></div></dl></div><div className="context-card"><small>ACTIVITY</small><div className="activity"><Clock3 size={15} /><p><b>Run created</b><span>Just now · PactFlow</span></p></div>{steps.filter((step) => step.done).slice(-3).map((step) => <div className="activity" key={step.id}><Check size={15} /><p><b>{step.label}</b><span>Completed by workflow</span></p></div>)}</div></aside></div>{complete && run?.proof && <ProofCard proof={run.proof} />}</div>;
}

function ProofCard({ proof }: { proof: NonNullable<WorkflowRun["proof"]> }) { return <section className="proof-card"><div className="proof-success"><span><Check size={22} /></span><div><small>{proof.mode === "live" ? "VERIFIED ON SOLANA" : "PROOF READY · SIMULATED ATTESTATION"}</small><h2>Execution proof created</h2><p>This cryptographic commitment covers the workflow, approvals, and execution result without exposing private business data.</p></div></div><div className="proof-data"><div><small>PROOF HASH</small><code>{proof.proofHash}</code></div><div><small>TRANSACTION SIGNATURE · {proof.mode === "live" ? "LIVE" : "DEMO ADAPTER"}</small><code>{proof.signature}</code></div><div className="proof-meta"><span><small>NETWORK</small><b>{proof.network}</b></span><span><small>WORKFLOW VERSION</small><b>v1</b></span><span><small>STEPS</small><b>Complete</b></span></div>{proof.explorerUrl ? <a className="secondary-button proof-link" href={proof.explorerUrl} target="_blank" rel="noreferrer">View on Solana Explorer <ExternalLink size={14} /></a> : <button className="secondary-button" disabled>Explorer available with live adapter <ExternalLink size={14} /></button>}</div></section>; }
